{{ with .Values }}
{{- if index . "enabled" }}
{{- if eq "true" .enabled }}
{{ range $migr_name,$migr_value := .hookJob }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ tpl ($migr_value.name | toString) $ }}
  labels:
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: {{ .hook }}
    helm.sh/hook-weight: {{ .hook_weight | quote }}
    helm.sh/hook-delete-policy: {{ .hook_delete_policy }}
spec:
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ tpl ($migr_value.name | toString) $ }}-job
        release: {{ $.Release.Name }}
{{- if .podLabels }}
{{ toYaml .podLabels | indent 8 }}
{{- end }}
{{- if $migr_value.podAnnotations }}
      annotations:
{{ toYaml $migr_value.podAnnotations | indent 8 }}
{{- end }}
    spec:
      restartPolicy: OnFailure
        {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
        {{- end }}
{{- if .nodeSelector }}
      nodeSelector:
{{ toYaml .nodeSelector | indent 8 }}
{{- end }}
{{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if eq true $migr_value.securityContext.enabled }}
      securityContext:
        runAsUser: {{ $migr_value.securityContext.runAsUser }}
        runAsGroup: {{ $migr_value.securityContext.runAsGroup }}
        fsGroup: {{ $migr_value.securityContext.fsGroup }}
{{- end }}
      volumes:
        {{- if default false .sharedmounts }}
{{ if $.Values.volumes -}}
{{ tpl (toYaml $.Values.volumes) $ | trim | indent 8 }}
{{- end }}
        {{- end }}
      serviceAccountName: default
      containers:
      - name: {{ $.Release.Name }}
        image:  {{ tpl $.Values.image.repository $ }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
        volumeMounts:
        {{- if default false .sharedmounts }}
{{ if $.Values.volumeMounts -}}
{{ toYaml $.Values.volumeMounts | trim | indent 10 }}
{{- end }}
            {{- end }}
        env:
{{- range $ev_key, $ev_value :=  $.Values.extraEnv }}
{{- if (typeIs "string" $ev_value) }}
        - name: {{ $ev_key }}
          value: {{ $ev_value | quote }}
{{- else }}
        - name: {{ $ev_key }}
{{ toYaml $ev_value | indent 10 }}
{{- end }}
{{- end }}
        args:
          - /bin/sh
          - -c
          - {{ .cmd }}
        resources:
{{ toYaml $migr_value.resources | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
---
{{- end }}