{{ with .Values }}
{{- if index . "enabled" }}
{{- if eq "true" .enabled }}
{{- if .secret }}
{{- range $key, $value := .secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
  annotations:
    {{- range $key, $value := $.Values.podAnnotations }}
    {{   $key }}: {{ $value | quote }}
    {{- end }}
    {{- with .annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/managed-by-test: test
type: {{ tpl .type $ | indent 0 }}
data:
{{- range $key, $value := .data }}
  {{ $key }}:{{ tpl $value $ | b64enc |indent 1 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
