{{ with .Values }}
{{- if index . "enabled" }}
{{- if eq "true" .enabled }}
{{- if .externalService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .externalService.name }}
  labels:
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ .externalService.name }}
    app.kubernetes.io/instance: {{ .externalService.name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .externalService.type }}
  externalName: {{ .externalService.externalName }}
  ports:
    - port: {{ .externalService.port }}
      protocol: TCP
      name: {{ .externalService.name }}
  selector:
    app.kubernetes.io/name: {{ .externalService.name }}
    app.kubernetes.io/instance: {{ .externalService.name }}
{{- end }}
{{- end }}
{{- end }}
---
{{- end }}
