{{ with .Values }}
{{- if index . "enabled" }}
{{- if eq "true" .enabled }}
{{- if index . "serviceAccount" }}
{{- if eq true .serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name | default $.Release.Name }}
  labels:
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
---
{{- end }}
